#!/usr/bin/python3


import subprocess
import re
from python.image_diff import show


def main():
    log_file = get_log_file()
    print(log_file)

    with(open(log_file, "r")) as f:
        lines = f.readlines()
        for line in lines:
            if "Capturing" in line:
                # print(line)
                m = re.match(r".*Capturing (\S+) and comparing with (\S+).*", line)
                if m:
                    # print(f"cp {m.group(1)} {m.group(2)}")
                    show(m.group(1), m.group(2))


def get_log_file():
    log_file = subprocess.run("ls -1rt _testoutput/*/*.log",
                              shell=True,
                              capture_output=True)
    log_file = log_file.stdout.decode("utf-8").split("\n")
    log_file = log_file[-2]
    return log_file


if __name__ == '__main__':
    main()
